name: Build

on:
    workflow_call:
        inputs:
            artifact-suffix:
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Build Mod
              run: dotnet build --configuration Release ilvyion.NutrientDispenserDispensableFix.sln

            - name: Upload Mod Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: NutrientDispenserDispensableFix-${{ inputs.artifact-suffix }}
                  path: |
                      About/
                      Assemblies/
                      LICENSE
                      LICENSE.Apache-2.0
                      LICENSE.MIT
                      README.md
                      CHANGELOG.md
                      !**/.*
                      !About/*.pdn
                      !About/*.svg
                      !About/*.ttf
