name: Continuous Integration

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".gitignore"
        tags-ignore:
            # This will ignore release versions tagged with a version identifier. We'll
            # use a separate workflow for them later.
            - "v*"
    pull_request:
        paths-ignore:
            - ".gitignore"

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            artifact-suffix: ${{ github.sha }}
